;; OS X: allow entering special chars via Option key
(setq mac-option-modifier nil)

;; OS X: modifier keys
(setq mac-command-modifier 'meta)
(setq ns-function-modifier 'super)

;; Custom key bindings
(global-set-key (kbd "C-+")         'text-scale-increase)
(global-set-key (kbd "C--")         'text-scale-decrease)
(global-set-key (kbd "C-B")         'tkareine/backward-char-5)
(global-set-key (kbd "C-F")         'tkareine/forward-char-5)
(global-set-key (kbd "C-M-r")       'isearch-backward)
(global-set-key (kbd "C-M-s")       'isearch-forward)
(global-set-key (kbd "C-N")         'tkareine/next-line-5)
(global-set-key (kbd "C-P")         'tkareine/previous-line-5)
(global-set-key (kbd "C-c ?")       'dash-at-point)
(global-set-key (kbd "C-c A")       'ag)
(global-set-key (kbd "C-c C-c M-x") 'execute-extended-command)
(global-set-key (kbd "C-c D")       'ag-dired-regexp)
(global-set-key (kbd "C-c O")       'tkareine/open-url-at-point)
(global-set-key (kbd "C-c P")       'tkareine/file-path-to-clipboard)
(global-set-key (kbd "C-c S")       'ag-regexp)
(global-set-key (kbd "C-c SPC")     'helm-semantic-or-imenu)
(global-set-key (kbd "C-c a")       'ag-project-at-point)
(global-set-key (kbd "C-c c")       'comment-or-uncomment-region)
(global-set-key (kbd "C-c d")       'ag-project-dired-regexp)
(global-set-key (kbd "C-c g")       'magit-status)
(global-set-key (kbd "C-c h")       'helm-command-prefix)
(global-set-key (kbd "C-c j")       'tkareine/js2-mode-toggle-strict-missing-semi-warning)
(global-set-key (kbd "C-c s")       'ag-regexp-project-at-point)
(global-set-key (kbd "C-c t")       'delete-trailing-whitespace)
(global-set-key (kbd "C-c w")       'whitespace-mode)
(global-set-key (kbd "C-r")         'isearch-backward-regexp)
(global-set-key (kbd "C-s")         'isearch-forward-regexp)
(global-set-key (kbd "C-x C-b")     'ibuffer)
(global-set-key (kbd "C-ä")         'insert-register)
(global-set-key (kbd "C-ö")         'copy-to-register)
(global-set-key (kbd "M-J")         'delete-indentation)
(global-set-key (kbd "M-SPC")       'fixup-whitespace)
(global-set-key (kbd "M-j")         'tkareine/join-line)
(global-set-key (kbd "M-§")         'other-frame)
(global-set-key (kbd "M-ä")         'point-to-register)
(global-set-key (kbd "M-å")         'er/expand-region)
(global-set-key (kbd "M-ö")         'jump-to-register)
(global-set-key (kbd "s-F")         'find-file-at-point)
(global-set-key (kbd "s-SPC")       'hippie-expand)
(global-set-key (kbd "s-b")         'projectile-switch-to-buffer)
(global-set-key (kbd "s-d")         'projectile-find-dir)
(global-set-key (kbd "s-f")         'projectile-find-file)
(global-set-key [M-kp-delete]       'kill-word)
(global-set-key [S-down]            'windmove-down)
(global-set-key [S-left]            'windmove-left)
(global-set-key [S-right]           'windmove-right)
(global-set-key [S-up]              'windmove-up)
(global-set-key [kp-delete]         'delete-char)

;; Auto complete: advanced completion
;; <http://cx4a.org/software/auto-complete/manual.html#auto-complete_command>
(define-key ac-mode-map (kbd "C-u TAB") 'auto-complete)

;; Helm: switch bindings for TAB andn C-z
(define-key helm-map (kbd "TAB") 'helm-execute-persistent-action)
(define-key helm-map (kbd "C-z") 'helm-select-action)

;; Helm: make TAB work in terminal
(define-key helm-map (kbd "C-i") 'helm-execute-persistent-action)
